[workspace]

members = ["crates/*", "examples/rust", "test/rust", "test/rust-compat"]
resolver = "2"

[workspace.package]
version = "0.4.0"
license = "MIT/Apache-2.0"
repository = "https://github.com/planus-org/planus"
rust-version = "1.70"
edition = "2021"
