[workspace]
members = ["crates/*", "examples/rust", "test/rust", "test/rust-compat"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT/Apache-2.0"
repository = "https://github.com/planus-org/planus"
rust-version = "1.75"
version = "1.0.0"

[workspace.dependencies]
askama = "0.12"
bitflags = "2.6.0"
clap = { version = "4.5.20", features = ["derive", "color"] }
clap_complete = "4.5.37"
codespan = "0.11.1"
codespan-reporting = "0.11.1"
color-eyre = "0.6.3"
criterion = "0.5"
crossterm = "0.28.1"
derive_more = "1.0.0"
eyre = "0.6.12"
flatbuffers = { version = "=23.5.26", git = "https://github.com/google/flatbuffers.git", tag = "v23.5.26" }
fuzzy-matcher = "0.3.7"
hashbrown = "0.15.1"
heck = "0.5.0"
indexmap = "2.6.0"
lalrpop = "0.22.0"
lalrpop-util = "0.22.0"
logos = "0.14.2"
num-traits = "0.2.19"
rand = "0.8.5"
random_color = "1.0.0"
rust-lapper = "1.1.0"
serde = { version = "1.0.214", default-features = false }
serde_json = "1.0.132"
similar-asserts = "1.6.0"
static_assertions = "1.1.0"
string-interner = "0.17.0"
thiserror = "2.0.0"
tui = "0.19.0"
vec_map = "0.8.2"

# Our crates
array-init-cursor = { version = "0.2.0", path = "crates/array-init-cursor" }
planus = { version = "1.0.0", path = "crates/planus", default-features = false }
planus-buffer-inspection = { version = "1.0.0", path = "crates/planus-buffer-inspection" }
planus-codegen = { version = "1.0.0", path = "crates/planus-codegen" }
planus-inspector = { version = "1.0.0", path = "crates/planus-inspector" }
planus-lexer = { version = "1.0.0", path = "crates/planus-lexer" }
planus-translation = { version = "1.0.0", path = "crates/planus-translation" }
planus-types = { version = "1.0.0", path = "crates/planus-types" }

# used for doctests
planus-example = { path = "examples/rust" }
