[package]
name = "planus-example"
version.workspace = true
edition.workspace = true

[dependencies]
planus = { workspace = true, default-features = false }
serde = { workspace = true, default-features = false, features = [
  "derive",
  "std",
] }

[dev-dependencies]
serde_json.workspace = true
